# Package information
[pkg.vim] #the title entry will be the assumed name unless overrides exist for the current platform
    apt = "vim-apt" #all other k/v pairs assume the key is a package manager alias
    apk = "neovim"  #and the value is the name of that package for that specific manager

#TODO: these need to be verified
[pkg.golang]
    gvm = ""
    brew = "golang"
    yay = "golang"

[pkg.fd]
    apt = "fd-find"